baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Visualize | Designed by TEMPLATED | Adapted to Hugo by Branch Web Presence"
copyright = "&copy; Untitled. All rights reserved. Hugo Theme: [Branch Web Presence](https://www.branchwebpresence.com/). Design: [TEMPLATED](http://templated.co/). Demo Images: [Unsplash](http://unsplash.com/)."

[params]
header = [
  "This is **Visualize**, a responsive site template designed by [TEMPLATED](http://templated.co/)",
  "Adapted to [Hugo](http://gohugo.io/) by [Branch Web Presence](https://www.branchwebpresence.com/)",
  "and released for free under the Creative Commons License."]

[params.avatar]
src = "images/avatar.jpg"
alt = "Avatar"

[params.social]
twitter = "https://twitter.com/"
facebook = "https://www.facebook.com/"
instagram = "https://www.instagram.com/"
fivehundredpx = "https://500px.com"
email = "info@example.com"
